version: "3.8"
services:
    web: 
      image: ibling/frontend:latest #repo de dockerhub
      container_name: frontend
      ports:
        - "80:80"  #mapear el puerto 80 del contenedor al puerto 80 del host
      restart: unless-stopped
      
